# Generated by Django 4.2.7 on 2025-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saharathiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
