# Generated by Django 5.1.3 on 2025-09-20 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saharathiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(choices=[('OCD', 'OCD'), ('Neuropsychiatry', 'Neuropsychiatry'), ('De-addiction', 'De-addiction'), ('Child Psychiatry', 'Child Psychiatry'), ('Psychiatry', 'Psychiatry'), ('Mental Health', 'Mental Health'), ('Addiction Psychiatry', 'Addiction Psychiatry'), ('Geriatric Psychiatry', 'Geriatric Psychiatry')], max_length=50)),
                ('bio', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('availability', models.CharField(choices=[('Today', 'Today'), ('This Week', 'This Week'), ('Next Month', 'Next Month')], max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Virtual', 'Virtual Session'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saharathiapp.consultant')),
            ],
        ),
    ]
