# Generated by Django 4.2.7 on 2025-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saharathiapp', '0002_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
