# Generated by Django 4.2.7 on 2025-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='coping',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
