# Generated by Django 5.2.6 on 2025-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_weeklyreflection_journalentry_is_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreflection',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='coping',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='summary',
            field=models.TextField(default='No summary provided'),
        ),
    ]
